### ISSUE TITLE
some time i got issues with the script not detecting the user is already there

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [dnaeon/zabbix-ldap-sync#45]
Hello,

/usr/sbin/zabbix-ldap-sync -f zabbix-ldap-admins-sys.conf

>>> Creating user xxxx, member of Zabbix group toto

>>> Creating user U12345, member of Zabbix group TOT.TOT

Traceback (most recent call last):

  File "/usr/sbin/zabbix-ldap-sync", line 884, in <module>

    main()

  File "/usr/sbin/zabbix-ldap-sync", line 881, in main

    config.media_opt)

  File "/usr/sbin/zabbix-ldap-sync", line 631, in sync_users

    self.create_user(user, zabbix_grpid, user_opt)

  File "/usr/sbin/zabbix-ldap-sync", line 496, in create_user

    result = self.conn.user.create(user)

  File "/usr/lib64/python2.6/site-packages/pyzabbix/__init__.py", line 157, in fn

    args or kwargs

  File "/usr/lib64/python2.6/site-packages/pyzabbix/__init__.py", line 134, in do_request

    raise ZabbixAPIException(msg, response_json['error']['code'])

pyzabbix.ZabbixAPIException: (u'Error -32602: Invalid params., User with alias "U12345" already exists.', -32602)

**Comment by scoopex** [comment]
Seems to be related to non lowercase usernames and to be solved.
If it still persists, please provide additional debug information and raise new bug at https://github.com/zabbix-tooling/zabbix-ldap-sync.
