### ISSUE TITLE
UnboundLocalError: local variable 'result_attrs' referenced before assignment

### ISSUE THREAD

**Issue by StormKnight29** [dnaeon/zabbix-ldap-sync#52]
./zabbix-ldap-sync -f zabbix-ldap.conf
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 884, in <module>
    main()
  File "./zabbix-ldap-sync", line 881, in main
    config.media_opt)
  File "./zabbix-ldap-sync", line 610, in sync_users
    ldap_users = ldap_conn.get_group_members(eachGroup)
  File "./zabbix-ldap-sync", line 144, in get_group_members
    for member in result_attrs[group_member_attribute]:
UnboundLocalError: local variable 'result_attrs' referenced before assignment

**Comment by scoopex** [comment]
Probably your problem does not exist anymore.
Please retest your problem with the current release and create a new issue at new location of the project https://github.com/zabbix-tooling/zabbix-ldap-sync.
