### ISSUE TITLE
UnboundLocalError: local variable 'result_dn' referenced before assignment

### ISSUE THREAD

**Issue by StormKnight29** [dnaeon/zabbix-ldap-sync#53]
./zabbix-ldap-sync -f zabbix-ldap.conf -r
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 884, in <module>
    main()
  File "./zabbix-ldap-sync", line 881, in main
    config.media_opt)
  File "./zabbix-ldap-sync", line 610, in sync_users
    ldap_users = ldap_conn.get_group_members(eachGroup)
  File "./zabbix-ldap-sync", line 128, in get_group_members
    member_of_filter_dn = memberof_filter % result_dn
UnboundLocalError: local variable 'result_dn' referenced before assignment

**Comment by scoopex** [comment]
Probably your problem does not exist anymore.
Please retest your problem with the current release and create a new issue at new location of the project https://github.com/zabbix-tooling/zabbix-ldap-sync.
