### ISSUE TITLE
UnboundLocalError: local variable 'user' referenced before assignment

### ISSUE THREAD

**Issue by joaquin386** [dnaeon/zabbix-ldap-sync#56]
When extending the openldap user filter.

Such as: 
filteruser = (&(objectClass=posixAccount)(uid=%s)(associatedDomain=Zabbix))
from original:
filteruser = (&(objectClass=posixAccount)(uid=%s))

Exception:
./zabbix-ldap-sync -f zabbix-ldap.conf -n
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 883, in <module>
    main()
  File "./zabbix-ldap-sync", line 880, in main
    config.media_opt)
  File "./zabbix-ldap-sync", line 609, in sync_users
    ldap_users = ldap_conn.get_group_members(eachGroup)
  File "./zabbix-ldap-sync", line 210, in get_group_members
    final_listing[user] = dn
UnboundLocalError: local variable 'user' referenced before assignment

**Comment by joaquin386** [comment]
I needed to put the users on the correct Groups then I could used the user filter.
Closing case.
